apiVersion: v1
kind: Service
metadata:
  name: my-app-active
  namespace: prd
spec:
  selector:
    app: my-app-rollout
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-preview
  namespace: prd
spec:
  selector:
    app: my-app-rollout
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
