apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

nameSuffix: -stg

replicas:
  - name: myapp
    count: 2

patches:
  - path: replica_count.yaml 
    target:
      kind: Deployment
      name: my-app
